export const ADD_INCOME_CATEGORY = 'ADD_INCOME_CATEGORY';
export const ADD_EXPENSE_CATEGORY = 'ADD_EXPENSE_CATEGORY';
export const DELETE_EXPENSE_CATEGORY = 'DELETE_EXPENSE_CATEGORY';
export const DELETE_INCOME_CATEGORY = 'DELETE_INCOME_CATEGORY';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_EXPENSE_CATEGORY = 'UPDATE_EXPENSE_CATEGORY';
export const UPDATE_INCOME_CATEGORY = 'UPDATE_INCOME_CATEGORY';

